services:
  email_sender:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerrepo.progcom.ru/email_sender_oracle/email_sender_oracle:0.0.1
    container_name: email_sender
    volumes:
      - ./settings/settings.ini:/var/emailSender/settings/settings.ini:ro
      - ./logs:/var/emailSender/logs
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
